#!/usr/bin/env bash
# =========================================================================
# FROZEN run harness for hipBLASLt autoresearch.
#
# DO NOT EDIT THIS FILE.  The AI agent must only modify tune_config.py.
#
# Usage:
#   ./run.sh                 # One iteration (verify + benchmark + keep/revert)
#   ./run.sh --loop N        # Run N iterations
#   ./run.sh --loop 0        # Run forever
#   ./run.sh --use-bench     # Use hipblaslt-bench CLI instead of PyTorch
#
# The script:
#   1. Verifies tune_config.py is valid and kernel produces correct results
#   2. Benchmarks GEMM shapes using hipBLASLt
#   3. If score improves, commits tune_config.py; otherwise reverts
# =========================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

BEST_SCORE_FILE=".best_score"
ITERATION_LOG="iteration_log.jsonl"
EDITABLE_FILE="tune_config.py"

# Time budget per experiment (seconds)
TIME_BUDGET=${TIME_BUDGET:-300}

# Pass --use-bench to benchmark.py if requested
BENCH_EXTRA_ARGS=""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

get_best_score() {
    if [[ -f "$BEST_SCORE_FILE" ]]; then
        cat "$BEST_SCORE_FILE"
    else
        echo "999999"
    fi
}

save_best_score() {
    echo "$1" > "$BEST_SCORE_FILE"
}

extract_score() {
    grep -oP 'FINAL_SCORE=\K[-0-9.]+' <<< "$1" || echo "999999"
}

log_iteration() {
    local iteration="$1" score="$2" best="$3" kept="$4"
    local timestamp
    timestamp=$(date -Iseconds)
    echo "{\"iteration\": $iteration, \"score\": $score, \"best\": $best, \"kept\": $kept, \"timestamp\": \"$timestamp\"}" \
        >> "$ITERATION_LOG"
}

# ---------------------------------------------------------------------------
# One iteration
# ---------------------------------------------------------------------------

run_one_iteration() {
    local iteration="$1"
    local best_score
    best_score=$(get_best_score)

    echo ""
    echo "=================================================================="
    echo " Iteration $iteration  |  Best score: $best_score"
    echo "=================================================================="

    # Step 1: Correctness
    echo ""
    echo "--- Verifying correctness ---"
    if ! timeout "$TIME_BUDGET" python3 verify.py; then
        echo ""
        echo ">>> CORRECTNESS FAILED - reverting $EDITABLE_FILE"
        git checkout "$EDITABLE_FILE" 2>/dev/null || true
        log_iteration "$iteration" "999999" "$best_score" "false"
        return 1
    fi

    # Step 2: Benchmark
    echo ""
    echo "--- Running benchmark ---"
    local bench_output
    if ! bench_output=$(timeout "$TIME_BUDGET" python3 benchmark.py $BENCH_EXTRA_ARGS 2>&1); then
        echo ""
        echo ">>> BENCHMARK FAILED - reverting $EDITABLE_FILE"
        echo "$bench_output"
        git checkout "$EDITABLE_FILE" 2>/dev/null || true
        log_iteration "$iteration" "999999" "$best_score" "false"
        return 1
    fi

    echo "$bench_output"

    # Step 3: Compare
    local score
    score=$(extract_score "$bench_output")

    echo ""
    echo "--- Score: $score  (best: $best_score) ---"

    local improved
    improved=$(echo "$score < $best_score" | bc -l 2>/dev/null || echo "0")

    if [[ "$improved" == "1" ]]; then
        echo ">>> IMPROVED!  Keeping change."
        save_best_score "$score"
        git add "$EDITABLE_FILE" 2>/dev/null || true
        git commit -m "iter $iteration: score $score (was $best_score)" 2>/dev/null || true
        log_iteration "$iteration" "$score" "$score" "true"
        return 0
    else
        echo ">>> No improvement.  Reverting $EDITABLE_FILE."
        git checkout "$EDITABLE_FILE" 2>/dev/null || true
        log_iteration "$iteration" "$score" "$best_score" "false"
        return 1
    fi
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

main() {
    # Ensure git repo
    if ! git rev-parse --is-inside-work-tree &>/dev/null; then
        echo "Error: must be inside a git repository."
        echo "Run: git init && git add -A && git commit -m 'initial'"
        exit 1
    fi

    # Parse args
    local loop_count=1
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --loop)
                loop_count="${2:-0}"
                shift 2
                ;;
            --use-bench)
                BENCH_EXTRA_ARGS="--use-bench"
                shift
                ;;
            *)
                echo "Unknown arg: $1"
                exit 1
                ;;
        esac
    done

    # Baseline
    if [[ ! -f "$BEST_SCORE_FILE" ]]; then
        echo "No baseline.  Running initial benchmark..."
        echo ""
        if python3 verify.py; then
            local bench_output
            bench_output=$(python3 benchmark.py $BENCH_EXTRA_ARGS 2>&1)
            echo "$bench_output"
            local baseline_score
            baseline_score=$(extract_score "$bench_output")
            save_best_score "$baseline_score"
            git add "$EDITABLE_FILE" 2>/dev/null || true
            git commit -m "baseline: score $baseline_score" 2>/dev/null || true
            echo ""
            echo "Baseline score: $baseline_score"
        else
            echo "Baseline verification failed.  Fix $EDITABLE_FILE first."
            exit 1
        fi
    fi

    # Loop
    local i=1
    while true; do
        run_one_iteration "$i" || true
        i=$((i + 1))
        if [[ "$loop_count" -gt 0 ]] && [[ "$i" -gt "$loop_count" ]]; then
            break
        fi
    done

    echo ""
    echo "=================================================================="
    echo " Done.  Best score: $(get_best_score)"
    echo " See iteration_log.jsonl for history."
    echo " See last_result.json for per-shape breakdown."
    echo "=================================================================="
}

main "$@"
