#!/usr/bin/env python3
"""
FROZEN correctness verification for autoresearch-cublas-sam3.

DO NOT EDIT THIS FILE.  The AI agent must only modify tune_config.py.

Works on both NVIDIA (cuBLASLt) and AMD (hipBLASLt) GPUs.

Exits 0 if correct, non-zero otherwise.
"""

import sys
import torch
import tune_config


TEST_SHAPES = [
    # Edge cases
    (1, 1, 1,             "trivial"),
    (1, 128, 128,         "single_row"),
    (16, 16, 16,          "tiny"),
    # SAM3 shapes
    (5184, 36288,  256,   "trk_xattn_qk"),
    (5184,   256, 36288,  "trk_xattn_v"),
    (5184,  4736, 1024,   "vit_g_mlp_up"),
    (5184,  1024, 4736,   "vit_g_mlp_down"),
    (5184,  3072, 1024,   "vit_g_qkv"),
    (5184,  1024, 1024,   "vit_g_out"),
    (576,   4736, 1024,   "vit_w_mlp_up"),
    (576,   1024, 4736,   "vit_w_mlp_down"),
    (5184,  2048,  256,   "det_enc_ffn"),
    (400,   5184,  256,   "det_xattn"),
    (32,    4096, 1024,   "txt_mlp_up"),
    # Non-power-of-2 stress tests
    (13, 37, 71,          "odd_dims"),
    (127, 513, 255,       "non_pow2"),
]

RTOL = 1e-2
ATOL = 1e-2


def verify_shape(M, N, K, label):
    """Verify one shape with all tuning settings applied."""
    dtype = tune_config.get_dtype()
    M_pad, N_pad, K_pad = tune_config.get_padded_shape(M, N, K)
    transpose_b = tune_config.should_transpose_b(M, N, K)

    a = torch.randn(M_pad, K_pad, device="cuda", dtype=dtype)
    if transpose_b:
        b_store = torch.randn(N_pad, K_pad, device="cuda", dtype=dtype)
        b_for_ref = b_store[:N, :K].t()  # (K, N) for reference
        out = torch.mm(a[:M, :K], b_store[:N, :K].t())
    else:
        b_store = torch.randn(K_pad, N_pad, device="cuda", dtype=dtype)
        b_for_ref = b_store[:K, :N]
        out = torch.matmul(a[:M, :K], b_store[:K, :N])

    # Reference (plain matmul, no tuning tricks)
    ref = torch.matmul(a[:M, :K].float(), b_for_ref.float()).to(dtype)

    if out.shape != ref.shape:
        print(f"  FAIL  {label:20s}  shape mismatch: {out.shape} vs {ref.shape}")
        return False

    max_diff = (out.float() - ref.float()).abs().max().item()
    passed = max_diff < ATOL + RTOL * ref.float().abs().max().item()

    flags = []
    if M_pad != M or N_pad != N or K_pad != K:
        flags.append(f"pad={M_pad}x{N_pad}x{K_pad}")
    if transpose_b:
        flags.append("NT")
    flag_str = f"  [{', '.join(flags)}]" if flags else ""

    status = "PASS" if passed else "FAIL"
    print(f"  {status}  {label:20s}  {M:5d}x{N:5d}x{K:5d}"
          f"  max_diff={max_diff:.6f}{flag_str}")

    return passed


def verify_config_sanity():
    """Check tune_config values are valid."""
    errors = []
    if tune_config.MATMUL_PRECISION not in ("highest", "high", "medium"):
        errors.append(f"MATMUL_PRECISION must be highest/high/medium, got {tune_config.MATMUL_PRECISION}")
    if tune_config.PREFERRED_BLAS not in ("default", "cublas", "cublaslt"):
        errors.append(f"PREFERRED_BLAS must be default/cublas/cublaslt, got {tune_config.PREFERRED_BLAS}")
    if tune_config.DTYPE not in ("float16", "bfloat16"):
        errors.append(f"DTYPE must be float16/bfloat16, got {tune_config.DTYPE}")
    if not isinstance(tune_config.PAD_TO_MULTIPLE, int) or tune_config.PAD_TO_MULTIPLE < 0:
        errors.append(f"PAD_TO_MULTIPLE must be non-negative int, got {tune_config.PAD_TO_MULTIPLE}")
    if not isinstance(tune_config.WORKSPACE_MB, (int, float)) or tune_config.WORKSPACE_MB < 0:
        errors.append(f"WORKSPACE_MB must be non-negative, got {tune_config.WORKSPACE_MB}")
    return errors


def main():
    print("=" * 72)
    print("autoresearch-cublas-sam3 Correctness Verification")
    print("=" * 72)

    # Config sanity
    print("\n--- Config check ---")
    errors = verify_config_sanity()
    if errors:
        for e in errors:
            print(f"  ERROR: {e}")
        sys.exit(1)
    print("  Config OK")

    if not torch.cuda.is_available():
        print("\nERROR: No GPU detected.")
        sys.exit(1)

    device_name = torch.cuda.get_device_name(0)
    is_amd = hasattr(torch.version, "hip") and torch.version.hip is not None
    print(f"  GPU: {device_name}")
    print(f"  Backend: {'hipBLASLt' if is_amd else 'cuBLASLt'}")
    print(f"  dtype: {tune_config.DTYPE}")
    print(f"  padding: {tune_config.PAD_TO_MULTIPLE}")

    # Apply settings
    tune_config.apply_global_settings()

    # Numerical verification
    print("\n--- Numerical verification ---")
    all_passed = True
    for M, N, K, label in TEST_SHAPES:
        if not verify_shape(M, N, K, label):
            all_passed = False

    print()
    print("=" * 72)
    if all_passed:
        print("ALL TESTS PASSED")
        sys.exit(0)
    else:
        print("SOME TESTS FAILED")
        sys.exit(1)


if __name__ == "__main__":
    main()
